<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>cmr_pecas_acessorios_api</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Dapper" Version="2.1.66" />
    <PackageReference Include="MySqlConnector" Version="2.4.0" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.6.2" />
    <PackageReference Include="System.Data.SqlClient" Version="4.9.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Cmr.Pecas.Acessorios.Infra\Cmr.Pecas.Acessorios.Infra.csproj" />
    <ProjectReference Include="..\Cmr.Pecas.Acessorios.Service\Cmr.Pecas.Acessorios.Service.csproj" />
  </ItemGroup>

</Project>
